### PR TITLE
Psp fix

### PR DESCRIPTION
**Pull request by ziporah**
You need to set all runAsUser to a non zero value if you are using psp
preferably user nobody

### CODE REVIEW

**Comment by dmitry-j-mikhin** [comment]
Thank you for PR, we will merge it in future release after testing.

**Comment by ziporah** [comment]
I updated the PR, with fixes for tarantool as well, I managed to get a full deployment up and running with this code

**Comment by lgg42** [comment]
Hello, any ETA for this fix? We just tried to use this chart's PSP in order to remove existing privileged PSP in the cluster, just to find out it's broken and makes the ingress controller pod crash.

**Comment by dmitry-j-mikhin** [comment]
> Hello, any ETA for this fix? We just tried to use this chart's PSP in order to remove existing privileged PSP in the cluster, just to find out it's broken and makes the ingress controller pod crash.

ETA - end of April

**Comment by dmitry-j-mikhin** [comment]
Merged in 9f375dcbcf2702d3d0a95667b866a7613755f2de

**Pull request closed without merging**
